apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-depl
  labels:
    app: ecom-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecom-product
  template:
    metadata:
      labels:
        app: ecom-product
    spec:
      containers:
        - name: prodcut
          image: cowculator99/ecom-product:latest
          env:
            - name: MONGO_URI
              value: mongodb://product-mongo-service:27017/products
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: ecom-product
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
